import type { CommandTokenBreakdown } from "./LabEngine";

export type CheatSheetCategory =
  | "All"
  | "Setup & Config"
  | "Create & Clone"
  | "Staging & Committing"
  | "Branching & Merging"
  | "Sharing & Remotes"
  | "Inspection & Logs"
  | "Undo & Reset"
  | "Stashing"
  | "Rebase & Advanced";

export type CheatSheetCommand = {
  id: string;
  category: Exclude<CheatSheetCategory, "All">;
  name: string;
  cmd: string;
  summary: string;
  commandMeaning: string;
  useCase: string;
  searchKeywords: string[];
  breakdown: CommandTokenBreakdown[];
  realWorldEffect: string;
  cheatSheetRef: string;
};

export const gitCheatSheetCommands: CheatSheetCommand[] = [
  // ==========================================
  // 1. SETUP & CONFIGURATION
  // ==========================================
  {
    id: "config-user-name",
    category: "Setup & Config",
    name: "Set Global Author Name",
    cmd: 'git config --global user.name "Your Name"',
    summary: "Sets the author name stamped onto all Git commits created across your system.",
    commandMeaning: "Saves your human developer name to ~/.gitconfig so every commit snapshot is properly signed with your identity.",
    useCase: "Required when setting up Git for the first time before making any open source contributions.",
    searchKeywords: [
      "command to set author name",
      "set name",
      "user name",
      "git name",
      "configure name",
      "change committer name",
      "git author",
      "who am i git",
      "identity setup",
    ],
    breakdown: [
      { token: "git", meaning: "Git distributed version control CLI" },
      { token: "config", meaning: "Inspects and sets configuration variables" },
      { token: "--global", meaning: "Applies setting across all repositories on your computer (~/.gitconfig)", isFlag: true },
      { token: "user.name", meaning: "Configuration key for public author name" },
      { token: '"Your Name"', meaning: "Your actual author name shown in git log" },
    ],
    realWorldEffect: "Writes to ~/.gitconfig. Maintainers see this name in git log and GitHub commit lists.",
    cheatSheetRef: "git-scm.com/cheat-sheet (Setup)",
  },
  {
    id: "config-user-email",
    category: "Setup & Config",
    name: "Set Global Author Email",
    cmd: 'git config --global user.email "your.email@example.com"',
    summary: "Links your commits to your GitHub account for green contribution squares.",
    commandMeaning: "Embeds your email address into commit metadata so GitHub links your work to your profile.",
    useCase: "Required for GitHub to associate your commits with your user profile and PR author avatar.",
    searchKeywords: [
      "command to set email",
      "set email",
      "user email",
      "configure email",
      "git email",
      "green contribution squares",
      "link commits to github profile",
    ],
    breakdown: [
      { token: "git", meaning: "Git distributed version control CLI" },
      { token: "config", meaning: "Inspects and sets configuration variables" },
      { token: "--global", meaning: "Applies setting machine-wide across all repositories", isFlag: true },
      { token: "user.email", meaning: "Configuration key for committer email address" },
      { token: '"your.email@..."', meaning: "Your verified GitHub email" },
    ],
    realWorldEffect: "GitHub reads this email from commit headers to award contribution credit on your profile.",
    cheatSheetRef: "git-scm.com/cheat-sheet (Setup)",
  },
  {
    id: "config-core-editor",
    category: "Setup & Config",
    name: "Set Default Text Editor",
    cmd: 'git config --global core.editor "code --wait"',
    summary: "Sets the default editor launched when writing commit messages or resolving interactive rebases.",
    commandMeaning: "Configures which terminal or GUI code editor opens when Git requires text input.",
    useCase: "Use when you want Git to open VS Code, Nano, or Vim instead of default Vi.",
    searchKeywords: [
      "command to set editor",
      "change git editor",
      "set vs code as editor",
      "default editor",
      "core editor",
      "git commit editor",
    ],
    breakdown: [
      { token: "git", meaning: "Git CLI" },
      { token: "config", meaning: "Configuration manager" },
      { token: "--global", meaning: "Machine-wide setting", isFlag: true },
      { token: "core.editor", meaning: "Configuration key for default text editor" },
      { token: '"code --wait"', meaning: "Launches VS Code and waits for window close" },
    ],
    realWorldEffect: "Git will open VS Code automatically for interactive git commit or git rebase -i.",
    cheatSheetRef: "git-scm.com/cheat-sheet (Setup)",
  },
  {
    id: "config-default-branch",
    category: "Setup & Config",
    name: "Set Default Branch to 'main'",
    cmd: "git config --global init.defaultBranch main",
    summary: "Ensures all new repositories created with 'git init' default to 'main' instead of 'master'.",
    commandMeaning: "Configures default initial branch name to align with modern open source naming conventions.",
    useCase: "Setting up a new development environment conforming to standard GitHub branch defaults.",
    searchKeywords: [
      "command to set default branch",
      "change master to main",
      "default branch main",
      "init default branch",
      "rename default branch",
    ],
    breakdown: [
      { token: "git", meaning: "Git CLI" },
      { token: "config", meaning: "Configuration manager" },
      { token: "--global", meaning: "Machine-wide setting", isFlag: true },
      { token: "init.defaultBranch", meaning: "Setting for default branch name in git init" },
      { token: "main", meaning: "Modern standard initial branch name" },
    ],
    realWorldEffect: "Every new 'git init' will start on 'main' branch automatically.",
    cheatSheetRef: "git-scm.com/cheat-sheet (Setup)",
  },
  {
    id: "config-list",
    category: "Setup & Config",
    name: "List All Git Settings",
    cmd: "git config --list --show-origin",
    summary: "Displays all active Git configuration variables and the exact file path where each is defined.",
    commandMeaning: "Inspects combined configuration from system, global, and local repository scopes.",
    useCase: "Troubleshooting author info, remote settings, or verifying that your setup is correct.",
    searchKeywords: [
      "command to view config",
      "show settings",
      "view git settings",
      "list config",
      "check author name",
      "check email",
      "where is git config",
    ],
    breakdown: [
      { token: "git", meaning: "Git CLI" },
      { token: "config", meaning: "Configuration manager" },
      { token: "--list", meaning: "List all active variables", isFlag: true },
      { token: "--show-origin", meaning: "Shows file path origin for each setting", isFlag: true },
    ],
    realWorldEffect: "Prints all settings without making any changes to your files.",
    cheatSheetRef: "git-scm.com/cheat-sheet (Setup)",
  },
  {
    id: "config-alias",
    category: "Setup & Config",
    name: "Create Git Command Alias / Shortcut",
    cmd: 'git config --global alias.co "checkout"',
    summary: "Creates a convenient CLI shorthand alias for long or frequently used Git commands.",
    commandMeaning: "Registers a custom abbreviation so you can type 'git co' instead of 'git checkout'.",
    useCase: "Speeding up daily terminal workflows with common shortcuts like 'co', 'br', 'st', 'ci'.",
    searchKeywords: [
      "command to create alias",
      "git shortcut",
      "create shorthand",
      "alias command",
      "git co checkout",
    ],
    breakdown: [
      { token: "git", meaning: "Git CLI" },
      { token: "config", meaning: "Configuration manager" },
      { token: "--global", meaning: "Machine-wide setting", isFlag: true },
      { token: "alias.co", meaning: "Defines alias name 'co'" },
      { token: '"checkout"', meaning: "Target command to execute" },
    ],
    realWorldEffect: "Typing 'git co' executes 'git checkout' directly.",
    cheatSheetRef: "git-scm.com/cheat-sheet (Setup)",
  },

  // ==========================================
  // 2. CREATE & CLONE PROJECTS
  // ==========================================
  {
    id: "create-init",
    category: "Create & Clone",
    name: "Initialize New Local Repository",
    cmd: "git init",
    summary: "Turns the current folder into a new local Git repository by creating a hidden .git directory.",
    commandMeaning: "Initializes version control tracking in an existing directory, setting up the object database and HEAD pointer.",
    useCase: "Starting a brand-new project from scratch on your local computer before pushing to GitHub.",
    searchKeywords: [
      "command to initialize git",
      "start new repo",
      "create git repo",
      "make repository",
      "git init",
      "initialize project",
      "start version control",
    ],
    breakdown: [
      { token: "git", meaning: "Git CLI" },
      { token: "init", meaning: "Creates an empty Git repository or reinitializes an existing one" },
    ],
    realWorldEffect: "Creates hidden .git/ directory on your disk. Your files become trackable.",
    cheatSheetRef: "git-scm.com/cheat-sheet (Create)",
  },
  {
    id: "create-init-name",
    category: "Create & Clone",
    name: "Create Folder & Initialize Repository",
    cmd: "git init my-new-project",
    summary: "Creates a new named folder and immediately initializes a Git repository inside it.",
    commandMeaning: "Combines directory creation (mkdir) and Git initialization (git init) in one step.",
    useCase: "Creating a new project scaffold without manually running mkdir and cd first.",
    searchKeywords: [
      "command to create new project folder",
      "init with folder name",
      "create repo in folder",
      "start new repo folder",
    ],
    breakdown: [
      { token: "git", meaning: "Git CLI" },
      { token: "init", meaning: "Initialize repository" },
      { token: "my-new-project", meaning: "Folder name to create and initialize" },
    ],
    realWorldEffect: "Creates folder ./my-new-project with an initialized .git folder.",
    cheatSheetRef: "git-scm.com/cheat-sheet (Create)",
  },
  {
    id: "clone-repo",
    category: "Create & Clone",
    name: "Clone Remote Repository",
    cmd: "git clone https://github.com/username/repository.git",
    summary: "Downloads a complete remote repository including all branches and full historical commits.",
    commandMeaning: "Copies remote repository over the network to your local disk and automatically configures 'origin' remote.",
    useCase: "Downloading your GitHub fork or an open source repository to start working on it.",
    searchKeywords: [
      "command to clone repo",
      "download repository",
      "copy github repo",
      "git clone",
      "download code from github",
      "clone fork",
      "get project",
    ],
    breakdown: [
      { token: "git", meaning: "Git CLI" },
      { token: "clone", meaning: "Copies repository and sets up local working directory" },
      { token: "https://...", meaning: "Remote repository URL (sets as 'origin')" },
    ],
    realWorldEffect: "Creates a project folder on your disk, tracks all branches, and sets origin remote URL.",
    cheatSheetRef: "git-scm.com/cheat-sheet (Create)",
  },
  {
    id: "clone-shallow",
    category: "Create & Clone",
    name: "Shallow Clone (Latest Commit Only)",
    cmd: "git clone --depth 1 https://github.com/username/repository.git",
    summary: "Clones only the most recent commit, saving massive disk space and download time for huge repos.",
    commandMeaning: "Truncates commit history to a single revision depth to download large codebases in seconds.",
    useCase: "CI/CD pipelines, quick code inspection, or contributing when bandwidth/disk is limited.",
    searchKeywords: [
      "command to clone fast",
      "shallow clone",
      "clone depth 1",
      "fast download repo",
      "download without history",
      "small clone",
    ],
    breakdown: [
      { token: "git", meaning: "Git CLI" },
      { token: "clone", meaning: "Download repository" },
      { token: "--depth 1", meaning: "Limits commit history depth to just 1 commit snapshot", isFlag: true },
      { token: "https://...", meaning: "Target repository URL" },
    ],
    realWorldEffect: "Downloads repository in seconds without gigabytes of old commit history.",
    cheatSheetRef: "git-scm.com/cheat-sheet (Create)",
  },

  // ==========================================
  // 3. STAGING & BASIC SNAPSHOTTING
  // ==========================================
  {
    id: "status-check",
    category: "Staging & Committing",
    name: "Check Workspace & Staging Status",
    cmd: "git status",
    summary: "Shows which files are modified, staged for the upcoming commit, or untracked by Git.",
    commandMeaning: "Compares the Working Tree against the Staging Index and HEAD commit to display exact file state.",
    useCase: "Run this command before staging, before committing, and before switching branches.",
    searchKeywords: [
      "command to check status",
      "check modified files",
      "what is changed",
      "git status",
      "see unstaged files",
      "check repo status",
      "working tree state",
    ],
    breakdown: [
      { token: "git", meaning: "Git CLI" },
      { token: "status", meaning: "Inspects working tree and staging index state" },
    ],
    realWorldEffect: "Safe command. Modifies nothing. Lists staged (green) and untracked/modified (red) files.",
    cheatSheetRef: "git-scm.com/cheat-sheet (Snapshotting)",
  },
  {
    id: "add-specific-file",
    category: "Staging & Committing",
    name: "Stage Specific File (git add)",
    cmd: "git add filename.txt",
    summary: "Moves a single modified or new file into the Git Staging Area (Index) ready for the next commit.",
    commandMeaning: "Stages the specified file snapshot into the Index, curating what will be included in the next commit.",
    useCase: "Use when you modified multiple files but only want to include this specific file in the upcoming commit.",
    searchKeywords: [
      "command to add file",
      "stage file",
      "add file to commit",
      "git add",
      "prepare file",
      "track file",
      "put file in commit",
      "stage single file",
      "stage changes",
    ],
    breakdown: [
      { token: "git", meaning: "Git CLI" },
      { token: "add", meaning: "Stages file changes into the Index" },
      { token: "filename.txt", meaning: "Specific target file path to stage" },
    ],
    realWorldEffect: "Moves file from unstaged (red) to staged (green). Ready to be committed.",
    cheatSheetRef: "git-scm.com/cheat-sheet (Snapshotting)",
  },
  {
    id: "add-all-files",
    category: "Staging & Committing",
    name: "Stage All Modified & New Files (git add .)",
    cmd: "git add .",
    summary: "Stages all modified, newly created, and deleted files in the current directory and subdirectories.",
    commandMeaning: "Recursively scans the current folder and adds all working tree changes into the Staging Index.",
    useCase: "Quickly staging all your local edits when all changes belong to the same logical commit.",
    searchKeywords: [
      "command to add all files",
      "stage everything",
      "git add .",
      "add all changes",
      "stage all modified files",
      "track all new files",
      "stage whole folder",
    ],
    breakdown: [
      { token: "git", meaning: "Git CLI" },
      { token: "add", meaning: "Stages changes into the Index" },
      { token: ".", meaning: "Wildcard representing current directory and all subdirectories", isFlag: true },
    ],
    realWorldEffect: "All modified and untracked files in the current folder turn green in 'git status'.",
    cheatSheetRef: "git-scm.com/cheat-sheet (Snapshotting)",
  },
  {
    id: "add-interactive-patch",
    category: "Staging & Committing",
    name: "Interactively Stage File Hunks (git add -p)",
    cmd: "git add -p",
    summary: "Interactively prompts you to review and stage individual line diffs (hunks) of files.",
    commandMeaning: "Opens interactive patch mode to selectively stage specific lines of code while leaving others unstaged.",
    useCase: "Essential for clean atomic commits when you made multiple unrelated edits in the same file.",
    searchKeywords: [
      "command to stage lines",
      "stage hunks",
      "interactive staging",
      "git add -p",
      "stage part of file",
      "selective staging",
      "patch mode",
    ],
    breakdown: [
      { token: "git", meaning: "Git CLI" },
      { token: "add", meaning: "Stage changes" },
      { token: "-p", meaning: "Patch flag to prompt for each hunk (y/n/s/e)", isFlag: true },
    ],
    realWorldEffect: "Lets you split changes in a single file across multiple separate clean commits.",
    cheatSheetRef: "git-scm.com/cheat-sheet (Snapshotting)",
  },
  {
    id: "commit-message",
    category: "Staging & Committing",
    name: "Save Commit Snapshot with Message",
    cmd: 'git commit -m "feat: add user authentication"',
    summary: "Records all currently staged files as a permanent snapshot with a unique SHA hash and commit description.",
    commandMeaning: "Packages staged changes into a new Git commit object and advances HEAD pointer to it.",
    useCase: "Saving verified units of work following Conventional Commits (feat, fix, docs, chore, refactor).",
    searchKeywords: [
      "command to commit",
      "save commit",
      "git commit",
      "make commit",
      "commit message",
      "save changes permanently",
      "record snapshot",
      "commit staged files",
    ],
    breakdown: [
      { token: "git", meaning: "Git CLI" },
      { token: "commit", meaning: "Records staged changes into repository version history" },
      { token: "-m", meaning: "Message flag to provide commit description inline without opening editor", isFlag: true },
      { token: '"feat: add..."', meaning: "Descriptive message summarizing the code changes" },
    ],
    realWorldEffect: "Creates a local commit with a SHA hash. Does NOT push to GitHub yet.",
    cheatSheetRef: "git-scm.com/cheat-sheet (Snapshotting)",
  },
  {
    id: "commit-all-tracked",
    category: "Staging & Committing",
    name: "Stage Tracked Files & Commit (git commit -am)",
    cmd: 'git commit -am "fix: resolve navigation bug"',
    summary: "Automatically stages all tracked modified files and creates a commit in a single step.",
    commandMeaning: "Combines 'git add' on all existing tracked files with 'git commit -m' in one command.",
    useCase: "Fast committing of existing modified files (Note: will NOT automatically track brand-new untracked files).",
    searchKeywords: [
      "command to add and commit in one step",
      "commit -am",
      "fast commit",
      "stage and commit together",
      "quick commit modified files",
    ],
    breakdown: [
      { token: "git", meaning: "Git CLI" },
      { token: "commit", meaning: "Record snapshot" },
      { token: "-a", meaning: "Automatically stage all modified tracked files", isFlag: true },
      { token: "-m", meaning: "Inline commit message flag", isFlag: true },
      { token: '"fix: resolve..."', meaning: "Commit message string" },
    ],
    realWorldEffect: "Stages modified tracked files and commits them in one go.",
    cheatSheetRef: "git-scm.com/cheat-sheet (Snapshotting)",
  },
  {
    id: "commit-amend",
    category: "Staging & Committing",
    name: "Amend / Fix Previous Commit",
    cmd: 'git commit --amend -m "feat: updated commit message"',
    summary: "Replaces the most recent commit with newly staged changes or an updated commit message.",
    commandMeaning: "Overwrites the latest commit snapshot on the current branch rather than creating a new separate commit.",
    useCase: "Fixing a typo in the last commit message or adding a forgotten file before pushing to GitHub.",
    searchKeywords: [
      "command to edit last commit",
      "amend commit",
      "change commit message",
      "fix last commit",
      "add file to previous commit",
      "modify top commit",
      "git commit --amend",
    ],
    breakdown: [
      { token: "git", meaning: "Git CLI" },
      { token: "commit", meaning: "Record snapshot" },
      { token: "--amend", meaning: "Replaces previous commit rather than creating a new one", isFlag: true },
      { token: "-m", meaning: "Updated commit message", isFlag: true },
    ],
    realWorldEffect: "Rewrites top commit hash. Only use before pushing to remote repository.",
    cheatSheetRef: "git-scm.com/cheat-sheet (Snapshotting)",
  },
  {
    id: "diff-working",
    category: "Staging & Committing",
    name: "Show Unstaged Working Tree Diffs",
    cmd: "git diff",
    summary: "Shows exact line-by-line additions and deletions in working files that have not yet been staged.",
    commandMeaning: "Compares current working directory modifications against the staging index.",
    useCase: "Reviewing code edits before running 'git add' to verify no debug logs or secrets were left behind.",
    searchKeywords: [
      "command to show differences",
      "see line changes",
      "git diff",
      "check unstaged changes",
      "view diff",
      "what did i edit",
    ],
    breakdown: [
      { token: "git", meaning: "Git CLI" },
      { token: "diff", meaning: "Computes and displays differences between file trees" },
    ],
    realWorldEffect: "Prints colored diff: green (+) for additions, red (-) for deletions.",
    cheatSheetRef: "git-scm.com/cheat-sheet (Snapshotting)",
  },
  {
    id: "diff-staged",
    category: "Staging & Committing",
    name: "Show Staged Diffs Ready for Commit",
    cmd: "git diff --staged",
    summary: "Shows exact line diffs of files that are already staged and will go into the next commit.",
    commandMeaning: "Compares the staging index against the last commit (HEAD) to preview the upcoming commit.",
    useCase: "Final sanity check before executing 'git commit' to confirm exactly what is being saved.",
    searchKeywords: [
      "command to see staged changes",
      "git diff --staged",
      "git diff --cached",
      "view commit preview",
      "see what is staged",
    ],
    breakdown: [
      { token: "git", meaning: "Git CLI" },
      { token: "diff", meaning: "Displays differences" },
      { token: "--staged", meaning: "Compares staging area against HEAD commit (same as --cached)", isFlag: true },
    ],
    realWorldEffect: "Displays only the changes that are queued up for the next commit.",
    cheatSheetRef: "git-scm.com/cheat-sheet (Snapshotting)",
  },
  {
    id: "rm-cached",
    category: "Staging & Committing",
    name: "Untrack File without Deleting from Disk",
    cmd: "git rm --cached sensitive.env",
    summary: "Stops tracking a file in Git and removes it from repo index while keeping the physical file on your disk.",
    commandMeaning: "Deletes file reference from the Git staging index without executing OS filesystem deletion.",
    useCase: "When you accidentally committed a .env, .DS_Store, or node_modules and want to add it to .gitignore.",
    searchKeywords: [
      "command to untrack file",
      "remove file from git keep on disk",
      "git rm --cached",
      "untrack secret file",
      "remove from repo without deleting",
      "ignore tracked file",
    ],
    breakdown: [
      { token: "git", meaning: "Git CLI" },
      { token: "rm", meaning: "Remove files from working tree and staging index" },
      { token: "--cached", meaning: "Removes from staging index only, leaving physical file intact", isFlag: true },
      { token: "sensitive.env", meaning: "Target file path to untrack" },
    ],
    realWorldEffect: "File remains safely on your computer drive, but Git stops tracking it.",
    cheatSheetRef: "git-scm.com/cheat-sheet (Snapshotting)",
  },

  // ==========================================
  // 4. BRANCHING & MERGING
  // ==========================================
  {
    id: "branch-list",
    category: "Branching & Merging",
    name: "List Local Branches",
    cmd: "git branch",
    summary: "Lists all local branches in the repository, with an asterisk (*) marking the current active HEAD branch.",
    commandMeaning: "Scans refs/heads/ to display all local branch pointers.",
    useCase: "Checking which branches exist and confirming which branch you are currently working on.",
    searchKeywords: [
      "command to list branches",
      "show branches",
      "git branch",
      "view all branches",
      "current branch",
      "which branch am i on",
    ],
    breakdown: [
      { token: "git", meaning: "Git CLI" },
      { token: "branch", meaning: "Lists, creates, or deletes branch pointers" },
    ],
    realWorldEffect: "Outputs branch names in terminal. Active branch is highlighted in green.",
    cheatSheetRef: "git-scm.com/cheat-sheet (Branching)",
  },
  {
    id: "branch-list-all",
    category: "Branching & Merging",
    name: "List Local & Remote Branches",
    cmd: "git branch -a",
    summary: "Lists all branches including remote-tracking branches from GitHub/origin.",
    commandMeaning: "Displays local branches alongside all remote refs in refs/remotes/.",
    useCase: "Checking what branches exist on the remote GitHub repository.",
    searchKeywords: [
      "command to list all branches",
      "see remote branches",
      "git branch -a",
      "list github branches",
      "show remote tracking branches",
    ],
    breakdown: [
      { token: "git", meaning: "Git CLI" },
      { token: "branch", meaning: "Branch manager" },
      { token: "-a", meaning: "Flag to list both local and remote branches (all)", isFlag: true },
    ],
    realWorldEffect: "Shows local branches and red remotes/origin/branch-name entries.",
    cheatSheetRef: "git-scm.com/cheat-sheet (Branching)",
  },
  {
    id: "checkout-new-branch",
    category: "Branching & Merging",
    name: "Create & Switch to New Feature Branch",
    cmd: "git checkout -b feature-login",
    summary: "Creates a new branch isolated from main and immediately switches your workspace to it.",
    commandMeaning: "Creates a new branch pointer and updates HEAD pointer and working tree to match.",
    useCase: "Rule #1 of Open Source: Always create a dedicated feature branch before making any changes.",
    searchKeywords: [
      "command to create branch",
      "create new branch",
      "git checkout -b",
      "make new branch and switch",
      "start new feature branch",
      "isolate branch",
    ],
    breakdown: [
      { token: "git", meaning: "Git CLI" },
      { token: "checkout", meaning: "Switches branches or restores working tree files" },
      { token: "-b", meaning: "Flag to create the branch first before checking it out", isFlag: true },
      { token: "feature-login", meaning: "The name of your new isolated branch" },
    ],
    realWorldEffect: "Isolates your code changes so your GitHub Pull Request stays clean and focused.",
    cheatSheetRef: "git-scm.com/cheat-sheet (Branching)",
  },
  {
    id: "switch-branch",
    category: "Branching & Merging",
    name: "Switch to Existing Branch (git switch / checkout)",
    cmd: "git switch main",
    summary: "Switches your working directory and HEAD pointer to an existing branch.",
    commandMeaning: "Updates working tree files to match the commit snapshot of the target branch.",
    useCase: "Switching back to 'main' branch to pull updates or jump between different features.",
    searchKeywords: [
      "command to switch branch",
      "change branch",
      "git switch",
      "git checkout main",
      "go to main branch",
      "switch active branch",
    ],
    breakdown: [
      { token: "git", meaning: "Git CLI" },
      { token: "switch", meaning: "Modern command dedicated to switching branches safely" },
      { token: "main", meaning: "Target branch name to activate" },
    ],
    realWorldEffect: "Swaps all files in your folder to match the state of that branch.",
    cheatSheetRef: "git-scm.com/cheat-sheet (Branching)",
  },
  {
    id: "branch-rename",
    category: "Branching & Merging",
    name: "Rename Current Branch",
    cmd: "git branch -m new-branch-name",
    summary: "Renames the current active branch to a new descriptive name.",
    commandMeaning: "Updates branch reference name in refs/heads/ while keeping all commit history intact.",
    useCase: "Fixing a typo in a branch name or renaming master to main.",
    searchKeywords: [
      "command to rename branch",
      "change branch name",
      "git branch -m",
      "rename current branch",
      "fix branch typo",
    ],
    breakdown: [
      { token: "git", meaning: "Git CLI" },
      { token: "branch", meaning: "Branch manager" },
      { token: "-m", meaning: "Move / rename flag", isFlag: true },
      { token: "new-branch-name", meaning: "New name for the branch" },
    ],
    realWorldEffect: "Renames the local branch without losing any commits.",
    cheatSheetRef: "git-scm.com/cheat-sheet (Branching)",
  },
  {
    id: "branch-delete-safe",
    category: "Branching & Merging",
    name: "Safely Delete Merged Branch",
    cmd: "git branch -d feature-login",
    summary: "Deletes a local branch that has already been merged into main.",
    commandMeaning: "Removes branch reference from refs/heads/ with safety check ensuring no unmerged commits are lost.",
    useCase: "Cleaning up local branches after your Pull Request has been merged on GitHub.",
    searchKeywords: [
      "command to delete branch",
      "remove branch",
      "git branch -d",
      "delete local branch",
      "cleanup merged branch",
    ],
    breakdown: [
      { token: "git", meaning: "Git CLI" },
      { token: "branch", meaning: "Branch manager" },
      { token: "-d", meaning: "Safe delete flag (errors if branch has unmerged work)", isFlag: true },
      { token: "feature-login", meaning: "Target branch name to delete" },
    ],
    realWorldEffect: "Removes branch from your local list. Commits remain safely in history if merged.",
    cheatSheetRef: "git-scm.com/cheat-sheet (Branching)",
  },
  {
    id: "branch-delete-force",
    category: "Branching & Merging",
    name: "Force Delete Branch (Unmerged Work)",
    cmd: "git branch -D abandoned-feature",
    summary: "Force deletes a local branch even if it contains unmerged commits.",
    commandMeaning: "Bypasses safety checks and forcibly removes branch pointer.",
    useCase: "Discarding an abandoned experiment or prototype that you no longer need.",
    searchKeywords: [
      "command to force delete branch",
      "delete unmerged branch",
      "git branch -D",
      "force remove branch",
      "discard branch",
    ],
    breakdown: [
      { token: "git", meaning: "Git CLI" },
      { token: "branch", meaning: "Branch manager" },
      { token: "-D", meaning: "Force delete flag (uppercase -D bypasses merge check)", isFlag: true },
      { token: "abandoned-feature", meaning: "Target branch to forcibly delete" },
    ],
    realWorldEffect: "Deletes the branch pointer immediately.",
    cheatSheetRef: "git-scm.com/cheat-sheet (Branching)",
  },
  {
    id: "merge-branch",
    category: "Branching & Merging",
    name: "Merge Branch into Current Branch",
    cmd: "git merge feature-login",
    summary: "Combines the specified branch's commit history into your current active branch.",
    commandMeaning: "Performs 3-way merge between current branch, target branch, and their common ancestor commit.",
    useCase: "Merging a completed feature branch into main locally.",
    searchKeywords: [
      "command to merge branch",
      "combine branches",
      "git merge",
      "integrate branch",
      "join branches",
      "fast forward merge",
    ],
    breakdown: [
      { token: "git", meaning: "Git CLI" },
      { token: "merge", meaning: "Combines independent branches into current HEAD" },
      { token: "feature-login", meaning: "Source branch containing commits to merge in" },
    ],
    realWorldEffect: "Brings all commits from feature-login into your active branch.",
    cheatSheetRef: "git-scm.com/cheat-sheet (Branching)",
  },
  {
    id: "merge-abort",
    category: "Branching & Merging",
    name: "Abort Merge on Conflicts",
    cmd: "git merge --abort",
    summary: "Cancels a merge in progress and restores your working directory to the exact state before the merge.",
    commandMeaning: "Resets HEAD and working tree to pre-merge state when encountering complex merge conflicts.",
    useCase: "Use when merge conflict markers get messy and you want to start fresh.",
    searchKeywords: [
      "command to cancel merge",
      "abort merge",
      "undo merge conflict",
      "git merge --abort",
      "stop merge",
      "exit merge conflict",
    ],
    breakdown: [
      { token: "git", meaning: "Git CLI" },
      { token: "merge", meaning: "Merge manager" },
      { token: "--abort", meaning: "Cancels current conflict resolution and resets to pre-merge state", isFlag: true },
    ],
    realWorldEffect: "Restores your branch safely to before you ran git merge.",
    cheatSheetRef: "git-scm.com/cheat-sheet (Branching)",
  },

  // ==========================================
  // 5. SHARING, REMOTES & SYNC
  // ==========================================
  {
    id: "remote-list",
    category: "Sharing & Remotes",
    name: "List Remote Repositories & URLs",
    cmd: "git remote -v",
    summary: "Shows all configured remote server aliases ('origin', 'upstream') and their fetch/push URLs.",
    commandMeaning: "Displays remote connection URLs stored in .git/config.",
    useCase: "Verifying whether your personal fork (origin) and maintainer repository (upstream) are configured.",
    searchKeywords: [
      "command to check remotes",
      "view remote urls",
      "git remote -v",
      "check origin upstream",
      "list github remotes",
    ],
    breakdown: [
      { token: "git", meaning: "Git CLI" },
      { token: "remote", meaning: "Manages tracked remote repositories" },
      { token: "-v", meaning: "Verbose flag to display URLs alongside remote names", isFlag: true },
    ],
    realWorldEffect: "Prints origin and upstream URLs without modifying anything.",
    cheatSheetRef: "git-scm.com/cheat-sheet (Remotes)",
  },
  {
    id: "remote-add-upstream",
    category: "Sharing & Remotes",
    name: "Connect Upstream Maintainer Repository",
    cmd: "git remote add upstream https://github.com/maintainer/repo.git",
    summary: "Registers the official maintainer repository as your 'upstream' remote so you can sync updates.",
    commandMeaning: "Adds a secondary remote connection alias named 'upstream' pointing to the original parent project.",
    useCase: "Standard setup for any open source contribution to keep your local fork in sync with maintainers.",
    searchKeywords: [
      "command to add upstream",
      "connect maintainer repo",
      "git remote add upstream",
      "add remote repository",
      "sync maintainer code",
      "setup upstream",
    ],
    breakdown: [
      { token: "git", meaning: "Git CLI" },
      { token: "remote", meaning: "Remote connection manager" },
      { token: "add", meaning: "Registers a new remote alias" },
      { token: "upstream", meaning: "Standard alias name representing official project repository" },
      { token: "https://...", meaning: "Official maintainer repository URL" },
    ],
    realWorldEffect: "Allows you to fetch official project updates via 'git fetch upstream'.",
    cheatSheetRef: "git-scm.com/cheat-sheet (Remotes)",
  },
  {
    id: "fetch-upstream",
    category: "Sharing & Remotes",
    name: "Fetch Latest Remote Commits",
    cmd: "git fetch upstream",
    summary: "Downloads new commits and branches from the maintainer repository into local cache without modifying working files.",
    commandMeaning: "Updates cached remote-tracking branches in refs/remotes/upstream/ safely in background.",
    useCase: "Checking for new upstream commits before rebasing or creating a new feature branch.",
    searchKeywords: [
      "command to fetch updates",
      "download latest commits",
      "git fetch upstream",
      "safely check updates",
      "fetch without merge",
      "update remote cache",
    ],
    breakdown: [
      { token: "git", meaning: "Git CLI" },
      { token: "fetch", meaning: "Downloads remote objects and refs into local cache safely" },
      { token: "upstream", meaning: "Target remote server alias" },
    ],
    realWorldEffect: "Updates local cache for upstream/main without touching your working files.",
    cheatSheetRef: "git-scm.com/cheat-sheet (Remotes)",
  },
  {
    id: "fetch-prune",
    category: "Sharing & Remotes",
    name: "Fetch & Prune Stale Remote Branches",
    cmd: "git fetch --prune origin",
    summary: "Downloads updates and removes local references to branches that were deleted on GitHub.",
    commandMeaning: "Synchronizes refs/remotes/origin with actual active branches on GitHub.",
    useCase: "Cleaning up clutter when maintainers delete merged branches on GitHub.",
    searchKeywords: [
      "command to prune branches",
      "clean deleted remote branches",
      "git fetch --prune",
      "sync deleted branches",
      "remove stale refs",
    ],
    breakdown: [
      { token: "git", meaning: "Git CLI" },
      { token: "fetch", meaning: "Download remote refs" },
      { token: "--prune", meaning: "Removes remote-tracking refs that no longer exist on remote", isFlag: true },
      { token: "origin", meaning: "Target remote" },
    ],
    realWorldEffect: "Deletes stale remotes/origin/branch pointers from your local machine.",
    cheatSheetRef: "git-scm.com/cheat-sheet (Remotes)",
  },
  {
    id: "pull-upstream",
    category: "Sharing & Remotes",
    name: "Pull & Merge Upstream Changes",
    cmd: "git pull upstream main",
    summary: "Downloads new commits from the maintainer repository and immediately merges them into your active branch.",
    commandMeaning: "Combines 'git fetch upstream' and 'git merge upstream/main' in one command.",
    useCase: "Updating your local main branch with the latest merged PRs from maintainers.",
    searchKeywords: [
      "command to pull changes",
      "download and merge",
      "git pull upstream",
      "update local code",
      "get latest changes",
      "sync main branch",
    ],
    breakdown: [
      { token: "git", meaning: "Git CLI" },
      { token: "pull", meaning: "Fetches from remote and immediately merges into active branch" },
      { token: "upstream", meaning: "Remote server alias" },
      { token: "main", meaning: "Target branch to pull from" },
    ],
    realWorldEffect: "Updates your working directory files with latest upstream code.",
    cheatSheetRef: "git-scm.com/cheat-sheet (Remotes)",
  },
  {
    id: "pull-rebase",
    category: "Sharing & Remotes",
    name: "Pull with Rebase (Clean Linear History)",
    cmd: "git pull --rebase upstream main",
    summary: "Fetches upstream commits and replays your local commits on top, avoiding ugly merge commits.",
    commandMeaning: "Combines 'git fetch' with 'git rebase' instead of 'git merge'.",
    useCase: "Best practice before opening or updating a Pull Request to keep commit history clean.",
    searchKeywords: [
      "command to pull rebase",
      "pull without merge commit",
      "git pull --rebase",
      "clean pull",
      "linear history pull",
    ],
    breakdown: [
      { token: "git", meaning: "Git CLI" },
      { token: "pull", meaning: "Fetch and integrate" },
      { token: "--rebase", meaning: "Replays local commits on top instead of creating a merge commit", isFlag: true },
      { token: "upstream", meaning: "Remote alias" },
      { token: "main", meaning: "Target branch" },
    ],
    realWorldEffect: "Produces a clean linear commit graph without unnecessary merge bubble commits.",
    cheatSheetRef: "git-scm.com/cheat-sheet (Remotes)",
  },
  {
    id: "push-branch",
    category: "Sharing & Remotes",
    name: "Push Feature Branch to GitHub (git push)",
    cmd: "git push -u origin feature-login",
    summary: "Uploads your local branch commits to your GitHub fork and sets up tracking for future pulls/pushes.",
    commandMeaning: "Transfers commit objects over network to GitHub and creates/updates the remote branch.",
    useCase: "Publishing your feature branch to GitHub so you can open a Pull Request.",
    searchKeywords: [
      "command to push to github",
      "upload branch",
      "git push",
      "publish branch",
      "push to origin",
      "create PR on github",
      "upload commits",
    ],
    breakdown: [
      { token: "git", meaning: "Git CLI" },
      { token: "push", meaning: "Uploads local branch commits to remote repository" },
      { token: "-u", meaning: "Sets upstream tracking reference for future 'git push'/'git pull'", isFlag: true },
      { token: "origin", meaning: "Target remote server alias (your personal GitHub fork)" },
      { token: "feature-login", meaning: "Branch name to create or update on GitHub" },
    ],
    realWorldEffect: "Creates branch on github.com and triggers the green 'Compare & pull request' banner.",
    cheatSheetRef: "git-scm.com/cheat-sheet (Remotes)",
  },
  {
    id: "push-delete-remote-branch",
    category: "Sharing & Remotes",
    name: "Delete Branch on Remote GitHub",
    cmd: "git push origin --delete feature-login",
    summary: "Deletes a branch directly from your remote GitHub repository over the network.",
    commandMeaning: "Sends instruction to remote server to delete branch reference in refs/heads/ on GitHub.",
    useCase: "Cleaning up old feature branches on your GitHub fork after PR is merged.",
    searchKeywords: [
      "command to delete remote branch",
      "remove branch from github",
      "git push --delete",
      "delete branch on origin",
      "cleanup remote branch",
    ],
    breakdown: [
      { token: "git", meaning: "Git CLI" },
      { token: "push", meaning: "Remote server interaction" },
      { token: "origin", meaning: "Remote repository alias" },
      { token: "--delete", meaning: "Instructs server to delete the specified branch", isFlag: true },
      { token: "feature-login", meaning: "Branch name to delete on GitHub" },
    ],
    realWorldEffect: "Removes the branch completely from your GitHub repository web interface.",
    cheatSheetRef: "git-scm.com/cheat-sheet (Remotes)",
  },
  {
    id: "push-force-lease",
    category: "Sharing & Remotes",
    name: "Safe Force Push (After Rebase)",
    cmd: "git push --force-with-lease origin feature-login",
    summary: "Safely force pushes rebased or amended commits to GitHub without overwriting teammates' work.",
    commandMeaning: "Updates remote branch ref only if nobody else has pushed new commits since your last fetch.",
    useCase: "Updating your GitHub PR after running 'git rebase' or 'git commit --amend'.",
    searchKeywords: [
      "command to force push safely",
      "git push --force-with-lease",
      "safe force push",
      "push after rebase",
      "update rebased PR",
      "overwrite remote branch safely",
    ],
    breakdown: [
      { token: "git", meaning: "Git CLI" },
      { token: "push", meaning: "Upload commits" },
      { token: "--force-with-lease", meaning: "Safe force push checking that remote ref hasn't changed unexpectedly", isFlag: true },
      { token: "origin", meaning: "Remote repository" },
      { token: "feature-login", meaning: "Target branch" },
    ],
    realWorldEffect: "Updates your PR commits on GitHub while protecting against accidental overwrite.",
    cheatSheetRef: "git-scm.com/cheat-sheet (Remotes)",
  },

  // ==========================================
  // 6. INSPECTION, LOGS & HISTORY
  // ==========================================
  {
    id: "log-history",
    category: "Inspection & Logs",
    name: "View Full Commit History (git log)",
    cmd: "git log",
    summary: "Displays chronological list of commits in current branch with author, date, SHA hash, and message.",
    commandMeaning: "Traverses commit graph starting from HEAD backwards through parent commits.",
    useCase: "Reviewing previous work, checking commit hashes, and inspecting author timestamps.",
    searchKeywords: [
      "command to view commit history",
      "show commits",
      "git log",
      "view git history",
      "see past commits",
      "commit log",
    ],
    breakdown: [
      { token: "git", meaning: "Git CLI" },
      { token: "log", meaning: "Displays chronological commit history" },
    ],
    realWorldEffect: "Opens scrollable pager showing author, date, hash, and commit description.",
    cheatSheetRef: "git-scm.com/cheat-sheet (Logs)",
  },
  {
    id: "log-oneline-graph",
    category: "Inspection & Logs",
    name: "Visual ASCII Commit Tree Graph",
    cmd: "git log --graph --oneline --decorate --all",
    summary: "Draws a beautiful visual text diagram of all branches, merges, and commit relationships.",
    commandMeaning: "Renders full DAG (directed acyclic graph) with colored branch lines and concise commit summaries.",
    useCase: "Visualizing complex branch merges, rebase states, and where HEAD is relative to main.",
    searchKeywords: [
      "command for visual git graph",
      "git tree graph",
      "git log --oneline --graph",
      "see branch tree",
      "visualize branches",
      "pretty git log",
    ],
    breakdown: [
      { token: "git", meaning: "Git CLI" },
      { token: "log", meaning: "Commit history" },
      { token: "--graph", meaning: "Draws ASCII art branch graph on the left", isFlag: true },
      { token: "--oneline", meaning: "Condenses each commit to 1 single line (hash + message)", isFlag: true },
      { token: "--decorate", meaning: "Shows branch and tag names on matching commits", isFlag: true },
      { token: "--all", meaning: "Includes all local and remote branches in the graph", isFlag: true },
    ],
    realWorldEffect: "Shows clear colored branch visual tree in terminal.",
    cheatSheetRef: "git-scm.com/cheat-sheet (Logs)",
  },
  {
    id: "log-file-history",
    category: "Inspection & Logs",
    name: "View Commit History for Specific File",
    cmd: "git log -p src/index.ts",
    summary: "Shows the complete commit history and line-by-line patch diffs that modified a specific file.",
    commandMeaning: "Filters commit history to revisions that touched the specified file and prints diff patches.",
    useCase: "Investigating when and why a specific file was changed or broken in past commits.",
    searchKeywords: [
      "command to view file history",
      "see changes to file in past",
      "git log for file",
      "file commit history",
      "who changed file",
    ],
    breakdown: [
      { token: "git", meaning: "Git CLI" },
      { token: "log", meaning: "Commit history" },
      { token: "-p", meaning: "Generates patch / line diff for each commit", isFlag: true },
      { token: "src/index.ts", meaning: "Specific target file path" },
    ],
    realWorldEffect: "Prints full historical changelog and diffs for that single file.",
    cheatSheetRef: "git-scm.com/cheat-sheet (Logs)",
  },
  {
    id: "blame-file",
    category: "Inspection & Logs",
    name: "Inspect Line-by-Line Authorship (git blame)",
    cmd: "git blame src/auth.ts",
    summary: "Annotates every line of a file with the author, commit hash, and timestamp of who last modified it.",
    commandMeaning: "Examines file history line-by-line to attribute the origin commit of each line of code.",
    useCase: "Finding out who wrote a specific function or line of code to ask questions or view the related PR.",
    searchKeywords: [
      "command to see who wrote line",
      "git blame",
      "line by line author",
      "who wrote this code",
      "check line author",
      "git annotate",
    ],
    breakdown: [
      { token: "git", meaning: "Git CLI" },
      { token: "blame", meaning: "Annotates each line in a file with commit revision and author info" },
      { token: "src/auth.ts", meaning: "Target file path to inspect" },
    ],
    realWorldEffect: "Outputs file content with author name and commit SHA prepended to every line.",
    cheatSheetRef: "git-scm.com/cheat-sheet (Logs)",
  },
  {
    id: "show-commit",
    category: "Inspection & Logs",
    name: "Show Commit Details & Diff (git show)",
    cmd: "git show a1b2c3d",
    summary: "Displays full commit metadata (author, date, message) and complete unified diff of that commit.",
    commandMeaning: "Inspects a specific commit object and displays its exact code changes.",
    useCase: "Viewing what was changed in a specific commit hash you found in git log.",
    searchKeywords: [
      "command to view commit details",
      "git show",
      "inspect commit hash",
      "see what commit did",
      "view commit patch",
    ],
    breakdown: [
      { token: "git", meaning: "Git CLI" },
      { token: "show", meaning: "Shows various types of Git objects (commits, tags, trees)" },
      { token: "a1b2c3d", meaning: "Commit SHA hash (or HEAD, tag, branch name)" },
    ],
    realWorldEffect: "Prints author info, commit message, and full file diffs for that commit.",
    cheatSheetRef: "git-scm.com/cheat-sheet (Logs)",
  },
  {
    id: "shortlog-contributors",
    category: "Inspection & Logs",
    name: "List Contributors & Commit Counts",
    cmd: "git shortlog -sn",
    summary: "Summarizes all repository contributors grouped by author and sorted by total number of commits.",
    commandMeaning: "Aggregates commit log by author and counts commits per developer.",
    useCase: "Viewing project contribution leaderboard and contributor roster.",
    searchKeywords: [
      "command to list contributors",
      "git shortlog",
      "see contributor ranking",
      "who committed most",
      "project authors list",
    ],
    breakdown: [
      { token: "git", meaning: "Git CLI" },
      { token: "shortlog", meaning: "Summarizes git log output" },
      { token: "-s", meaning: "Suppresses commit descriptions (summary only)", isFlag: true },
      { token: "-n", meaning: "Sorts numerically according to number of commits", isFlag: true },
    ],
    realWorldEffect: "Prints ranked list of authors with commit counts.",
    cheatSheetRef: "git-scm.com/cheat-sheet (Logs)",
  },

  // ==========================================
  // 7. UNDOING CHANGES & RESETTING
  // ==========================================
  {
    id: "restore-file",
    category: "Undo & Reset",
    name: "Discard Working File Changes (git restore)",
    cmd: "git restore filename.txt",
    summary: "Discards uncommitted modifications in a working file, reverting it back to the last commit snapshot.",
    commandMeaning: "Overwrites working tree file with the clean version from the staging index or HEAD.",
    useCase: "Throwing away experimental changes in a file and restoring the original working version.",
    searchKeywords: [
      "command to discard file changes",
      "undo file edits",
      "git restore",
      "revert file to clean",
      "throw away changes in file",
      "reset file to last commit",
      "git checkout -- file",
    ],
    breakdown: [
      { token: "git", meaning: "Git CLI" },
      { token: "restore", meaning: "Restores working tree files to clean state" },
      { token: "filename.txt", meaning: "Target file to discard changes in" },
    ],
    realWorldEffect: "Permanent action. Uncommitted modifications in filename.txt are discarded.",
    cheatSheetRef: "git-scm.com/cheat-sheet (Undo)",
  },
  {
    id: "restore-unstage",
    category: "Undo & Reset",
    name: "Unstage File (Remove from Staging Index)",
    cmd: "git restore --staged filename.txt",
    summary: "Removes a file from the Staging Area while keeping your actual code edits safely in your working directory.",
    commandMeaning: "Copies file state from HEAD into staging index without touching your working directory.",
    useCase: "When you ran 'git add' by mistake on a file and want to unstage it before committing.",
    searchKeywords: [
      "command to unstage file",
      "unstage changes",
      "git restore --staged",
      "git reset HEAD file",
      "remove from staging",
      "undo git add",
      "take file out of staging",
    ],
    breakdown: [
      { token: "git", meaning: "Git CLI" },
      { token: "restore", meaning: "Restore files" },
      { token: "--staged", meaning: "Unstages the file from the Index while keeping file edits intact", isFlag: true },
      { token: "filename.txt", meaning: "Target file to unstage" },
    ],
    realWorldEffect: "File turns from green (staged) back to red (modified) in 'git status'. No code is lost.",
    cheatSheetRef: "git-scm.com/cheat-sheet (Undo)",
  },
  {
    id: "restore-all",
    category: "Undo & Reset",
    name: "Discard All Unstaged Changes",
    cmd: "git restore .",
    summary: "Discards all unstaged modifications across the current directory and subdirectories.",
    commandMeaning: "Recursively restores all working directory files to match the staging index or HEAD.",
    useCase: "Resetting your workspace to a clean slate after an experiment didn't work.",
    searchKeywords: [
      "command to discard all changes",
      "undo all edits",
      "git restore .",
      "reset workspace to clean",
      "discard working tree changes",
    ],
    breakdown: [
      { token: "git", meaning: "Git CLI" },
      { token: "restore", meaning: "Restores working tree files" },
      { token: ".", meaning: "Applies to all files in current folder", isFlag: true },
    ],
    realWorldEffect: "Permanently reverts all unstaged modified files to the clean HEAD state.",
    cheatSheetRef: "git-scm.com/cheat-sheet (Undo)",
  },
  {
    id: "revert-commit",
    category: "Undo & Reset",
    name: "Revert Commit by Creating Inverted Commit",
    cmd: "git revert a1b2c3d",
    summary: "Creates a brand-new commit that undoes the exact changes introduced in a past commit.",
    commandMeaning: "Calculates inverse patch of target commit and commits it as a new revision without rewriting history.",
    useCase: "Safest way to undo a bug in production or on main branch because it preserves public Git history.",
    searchKeywords: [
      "command to revert commit",
      "undo pushed commit",
      "git revert",
      "safe commit undo",
      "reverse commit",
      "undo public commit",
    ],
    breakdown: [
      { token: "git", meaning: "Git CLI" },
      { token: "revert", meaning: "Records new commit that inverts changes from specified commit" },
      { token: "a1b2c3d", meaning: "Target commit SHA to undo" },
    ],
    realWorldEffect: "Creates a new commit e.g. 'Revert \"feat: ...\"'. Safe for public shared branches.",
    cheatSheetRef: "git-scm.com/cheat-sheet (Undo)",
  },
  {
    id: "reset-soft",
    category: "Undo & Reset",
    name: "Undo Last Commit (Keep Files Staged)",
    cmd: "git reset --soft HEAD~1",
    summary: "Undoes the most recent commit, moving your branch back 1 commit while keeping all changes staged in the index.",
    commandMeaning: "Moves HEAD pointer back 1 commit without touching staging index or working directory.",
    useCase: "When you committed too early and want to add more files or adjust the commit message cleanly.",
    searchKeywords: [
      "command to undo last commit",
      "git reset --soft",
      "undo commit keep staged",
      "uncommit changes",
      "take back last commit",
      "undo commit keep changes",
    ],
    breakdown: [
      { token: "git", meaning: "Git CLI" },
      { token: "reset", meaning: "Resets current HEAD to specified state" },
      { token: "--soft", meaning: "Keeps all file changes in the staging index ready to re-commit", isFlag: true },
      { token: "HEAD~1", meaning: "Target commit (1 commit before current HEAD)" },
    ],
    realWorldEffect: "Commit disappears from log, but all modified files stay staged (green) in 'git status'.",
    cheatSheetRef: "git-scm.com/cheat-sheet (Undo)",
  },
  {
    id: "reset-mixed",
    category: "Undo & Reset",
    name: "Undo Last Commit (Keep Files Unstaged)",
    cmd: "git reset HEAD~1",
    summary: "Undoes the last commit, leaving all your modified files in your working directory unstaged.",
    commandMeaning: "Default reset mode (--mixed). Moves HEAD back and resets staging index while preserving working files.",
    useCase: "Splitting a large commit into multiple smaller atomic commits.",
    searchKeywords: [
      "command to uncommit",
      "git reset HEAD~1",
      "undo commit keep files",
      "split commit",
      "undo commit unstaged",
    ],
    breakdown: [
      { token: "git", meaning: "Git CLI" },
      { token: "reset", meaning: "Resets HEAD pointer" },
      { token: "HEAD~1", meaning: "Target revision (1 commit prior)" },
    ],
    realWorldEffect: "Commit is undone; your file edits remain safe in your working directory (red).",
    cheatSheetRef: "git-scm.com/cheat-sheet (Undo)",
  },
  {
    id: "reset-hard",
    category: "Undo & Reset",
    name: "Permanently Destroy Last Commit & Changes",
    cmd: "git reset --hard HEAD~1",
    summary: "Completely obliterates the last commit and permanently throws away all associated file changes.",
    commandMeaning: "Forcibly resets HEAD, staging index, and working tree to match target commit.",
    useCase: "Permanently wiping out a disastrous local commit that you want completely gone.",
    searchKeywords: [
      "command to destroy last commit",
      "git reset --hard",
      "wipe out commit",
      "delete last commit completely",
      "nuclear reset",
      "discard commit and changes",
    ],
    breakdown: [
      { token: "git", meaning: "Git CLI" },
      { token: "reset", meaning: "Resets HEAD" },
      { token: "--hard", meaning: "Discards all staged and working directory modifications", isFlag: true },
      { token: "HEAD~1", meaning: "Target commit" },
    ],
    realWorldEffect: "CAUTION: Irreversible. Commit and all file edits made in it are completely deleted.",
    cheatSheetRef: "git-scm.com/cheat-sheet (Undo)",
  },
  {
    id: "clean-untracked",
    category: "Undo & Reset",
    name: "Remove Untracked Files & Folders",
    cmd: "git clean -fd",
    summary: "Forcibly deletes all untracked files and directories that are not in your .gitignore.",
    commandMeaning: "Cleans the working tree by removing files that are not tracked in Git version control.",
    useCase: "Cleaning build artifacts, generated temp files, or unwanted new files from workspace.",
    searchKeywords: [
      "command to delete untracked files",
      "git clean",
      "remove untracked files",
      "clean working directory",
      "delete untracked folders",
    ],
    breakdown: [
      { token: "git", meaning: "Git CLI" },
      { token: "clean", meaning: "Removes untracked files from working tree" },
      { token: "-f", meaning: "Force flag (required by Git configuration to avoid accidental deletion)", isFlag: true },
      { token: "-d", meaning: "Removes untracked directories in addition to files", isFlag: true },
    ],
    realWorldEffect: "Permanently deletes untracked files and folders from disk.",
    cheatSheetRef: "git-scm.com/cheat-sheet (Undo)",
  },

  // ==========================================
  // 8. TEMPORARY STASHING
  // ==========================================
  {
    id: "stash-save",
    category: "Stashing",
    name: "Save Work to Stash Temporarily (git stash)",
    cmd: 'git stash push -m "wip: halfway through login logic"',
    summary: "Temporarily shelves uncommitted changes to give you a clean working directory without committing.",
    commandMeaning: "Saves working tree and staging index modifications onto the stash stack and resets to clean HEAD.",
    useCase: "When you need to urgently switch branches or pull upstream code without creating a half-finished commit.",
    searchKeywords: [
      "command to stash changes",
      "save work temporarily",
      "git stash",
      "git stash push",
      "hide changes",
      "shelve changes",
      "clean workspace without commit",
      "switch branch with dirty tree",
    ],
    breakdown: [
      { token: "git", meaning: "Git CLI" },
      { token: "stash", meaning: "Stashes modifications in a dirty working directory" },
      { token: "push", meaning: "Saves new stash onto the stash stack" },
      { token: "-m", meaning: "Descriptive message label for the stash entry", isFlag: true },
      { token: '"wip: halfway..."', meaning: "Label describing what was stashed" },
    ],
    realWorldEffect: "Working directory becomes completely clean (HEAD). Your changes are safely stored in stash.",
    cheatSheetRef: "git-scm.com/cheat-sheet (Stash)",
  },
  {
    id: "stash-include-untracked",
    category: "Stashing",
    name: "Stash All Files Including Untracked (-u)",
    cmd: "git stash -u",
    summary: "Stashes modified files as well as newly created untracked files.",
    commandMeaning: "Includes files not yet tracked by Git into the saved stash object.",
    useCase: "When you created new files that are not yet tracked and need to stash everything.",
    searchKeywords: [
      "command to stash untracked files",
      "git stash -u",
      "git stash --include-untracked",
      "stash new files",
      "stash everything",
    ],
    breakdown: [
      { token: "git", meaning: "Git CLI" },
      { token: "stash", meaning: "Stash manager" },
      { token: "-u", meaning: "Includes untracked files in the stash entry", isFlag: true },
    ],
    realWorldEffect: "Even brand new untracked files disappear from workspace and go into stash.",
    cheatSheetRef: "git-scm.com/cheat-sheet (Stash)",
  },
  {
    id: "stash-list",
    category: "Stashing",
    name: "List All Saved Stashes",
    cmd: "git stash list",
    summary: "Displays all saved stash entries on the stack with their index numbers (e.g. stash@{0}).",
    commandMeaning: "Inspects refs/stash reflog to show all stored stash snapshots.",
    useCase: "Viewing what stashes you have saved before applying or popping one.",
    searchKeywords: [
      "command to list stashes",
      "view saved stashes",
      "git stash list",
      "see stash history",
      "show stash stack",
    ],
    breakdown: [
      { token: "git", meaning: "Git CLI" },
      { token: "stash", meaning: "Stash manager" },
      { token: "list", meaning: "Lists all stored stash entries" },
    ],
    realWorldEffect: "Prints list of stashes: stash@{0}: WIP on main...",
    cheatSheetRef: "git-scm.com/cheat-sheet (Stash)",
  },
  {
    id: "stash-pop",
    category: "Stashing",
    name: "Restore & Remove Top Stash (git stash pop)",
    cmd: "git stash pop",
    summary: "Applies the most recent stash changes back to your working directory and removes it from the stash list.",
    commandMeaning: "Applies stash@{0} to working tree and deletes it from stash stack if applied successfully.",
    useCase: "Resuming work on your shelved changes after switching back to your feature branch.",
    searchKeywords: [
      "command to restore stash",
      "apply stash and remove",
      "git stash pop",
      "get stashed changes back",
      "unstash work",
      "resume stashed work",
    ],
    breakdown: [
      { token: "git", meaning: "Git CLI" },
      { token: "stash", meaning: "Stash manager" },
      { token: "pop", meaning: "Applies stash@{0} and drops it from the stash stack" },
    ],
    realWorldEffect: "Your stashed modifications reappear in your working files.",
    cheatSheetRef: "git-scm.com/cheat-sheet (Stash)",
  },
  {
    id: "stash-apply",
    category: "Stashing",
    name: "Apply Stash without Removing It",
    cmd: "git stash apply stash@{1}",
    summary: "Applies a specific stash entry to your working directory while keeping it safely on the stash stack.",
    commandMeaning: "Applies specified stash snapshot without dropping it from the stash list.",
    useCase: "Reusing the same stash across multiple branches or testing changes without losing the stash.",
    searchKeywords: [
      "command to apply specific stash",
      "git stash apply",
      "apply stash keep copy",
      "restore numbered stash",
    ],
    breakdown: [
      { token: "git", meaning: "Git CLI" },
      { token: "stash", meaning: "Stash manager" },
      { token: "apply", meaning: "Applies changes to working tree without removing from stack" },
      { token: "stash@{1}", meaning: "Target numbered stash index" },
    ],
    realWorldEffect: "Modifications are restored in your files, and the stash remains saved.",
    cheatSheetRef: "git-scm.com/cheat-sheet (Stash)",
  },
  {
    id: "stash-drop-clear",
    category: "Stashing",
    name: "Delete Stash Entry or Clear All",
    cmd: "git stash drop stash@{0}",
    summary: "Deletes a specific stash from the stash stack (or use 'git stash clear' to delete all).",
    commandMeaning: "Removes target stash object from refs/stash stack.",
    useCase: "Cleaning up old stashes that you no longer need.",
    searchKeywords: [
      "command to delete stash",
      "git stash drop",
      "git stash clear",
      "remove saved stash",
      "delete all stashes",
    ],
    breakdown: [
      { token: "git", meaning: "Git CLI" },
      { token: "stash", meaning: "Stash manager" },
      { token: "drop", meaning: "Removes specific stash from stack" },
      { token: "stash@{0}", meaning: "Target stash index to delete" },
    ],
    realWorldEffect: "Deletes the stash entry.",
    cheatSheetRef: "git-scm.com/cheat-sheet (Stash)",
  },

  // ==========================================
  // 9. REBASING, TAGGING & ADVANCED
  // ==========================================
  {
    id: "rebase-upstream-main",
    category: "Rebase & Advanced",
    name: "Rebase Branch onto Upstream/Main",
    cmd: "git rebase upstream/main",
    summary: "Replays your branch commits cleanly on top of the newest upstream code for a linear history.",
    commandMeaning: "Rewinds HEAD to upstream/main and reapplies local feature commits one by one on top.",
    useCase: "Mandatory in open source to resolve conflicts and keep commit history linear before PR merge.",
    searchKeywords: [
      "command to rebase",
      "git rebase upstream/main",
      "update branch with upstream",
      "reapply commits on main",
      "linear commit history",
      "sync PR with maintainer",
    ],
    breakdown: [
      { token: "git", meaning: "Git CLI" },
      { token: "rebase", meaning: "Reapplies commits on top of another base tip" },
      { token: "upstream/main", meaning: "Target maintainer branch containing latest merged PRs" },
    ],
    realWorldEffect: "Eliminates merge conflicts and places your commits at the top of the history.",
    cheatSheetRef: "git-scm.com/cheat-sheet (Rebase)",
  },
  {
    id: "rebase-interactive-squash",
    category: "Rebase & Advanced",
    name: "Interactive Rebase & Squash Commits",
    cmd: "git rebase -i HEAD~3",
    summary: "Opens interactive editor to squash (combine), edit, reword, reorder, or drop the last 3 commits.",
    commandMeaning: "Launches interactive rebase script allowing full curation of recent commit history.",
    useCase: "Squashing 'fix typo', 'wip', and 'oops' commits into 1 clean atomic commit before PR review.",
    searchKeywords: [
      "command to squash commits",
      "git rebase -i",
      "combine commits",
      "interactive rebase",
      "clean up commits before PR",
      "reword commit",
      "drop commit",
      "squash 3 commits",
    ],
    breakdown: [
      { token: "git", meaning: "Git CLI" },
      { token: "rebase", meaning: "Rebase engine" },
      { token: "-i", meaning: "Interactive mode flag (opens editor list: pick, squash, reword, drop)", isFlag: true },
      { token: "HEAD~3", meaning: "Scope (last 3 commits)" },
    ],
    realWorldEffect: "Lets you combine messy commits into 1 clean professional commit for maintainers.",
    cheatSheetRef: "git-scm.com/cheat-sheet (Rebase)",
  },
  {
    id: "cherry-pick-commit",
    category: "Rebase & Advanced",
    name: "Cherry-Pick Commit from Another Branch",
    cmd: "git cherry-pick a1b2c3d",
    summary: "Copies a specific commit from another branch and applies it directly onto your current active branch.",
    commandMeaning: "Extracts patch from target commit and creates a new commit on current branch.",
    useCase: "Porting a critical bug fix or specific feature commit from another branch without merging the whole branch.",
    searchKeywords: [
      "command to cherry pick",
      "git cherry-pick",
      "copy commit from another branch",
      "apply single commit",
      "port commit",
    ],
    breakdown: [
      { token: "git", meaning: "Git CLI" },
      { token: "cherry-pick", meaning: "Applies changes introduced by existing commit onto current HEAD" },
      { token: "a1b2c3d", meaning: "Target commit SHA hash" },
    ],
    realWorldEffect: "Creates a new commit on your branch containing exact changes from target commit.",
    cheatSheetRef: "git-scm.com/cheat-sheet (Advanced)",
  },
  {
    id: "tag-create-annotated",
    category: "Rebase & Advanced",
    name: "Create Annotated Release Tag",
    cmd: 'git tag -a v1.0.0 -m "Release version 1.0.0"',
    summary: "Creates a permanent signed release tag pointing to the current commit with release notes.",
    commandMeaning: "Creates an annotated tag object containing tagger name, email, date, and message.",
    useCase: "Marking official software version releases (v1.0.0, v2.1.0) on GitHub.",
    searchKeywords: [
      "command to create tag",
      "git tag",
      "make release tag",
      "create version tag",
      "release version v1.0.0",
      "tag release",
    ],
    breakdown: [
      { token: "git", meaning: "Git CLI" },
      { token: "tag", meaning: "Tag manager" },
      { token: "-a", meaning: "Creates annotated tag object (with author, date, message)", isFlag: true },
      { token: "v1.0.0", meaning: "Semantic version tag name" },
      { token: "-m", meaning: "Release message flag", isFlag: true },
      { token: '"Release..."', meaning: "Release description" },
    ],
    realWorldEffect: "Creates tag locally. Push to GitHub with 'git push origin v1.0.0' to create a GitHub Release.",
    cheatSheetRef: "git-scm.com/cheat-sheet (Tagging)",
  },
  {
    id: "tag-push-remote",
    category: "Rebase & Advanced",
    name: "Push Tags to GitHub",
    cmd: "git push origin --tags",
    summary: "Uploads all local tags to your remote GitHub repository to publish releases.",
    commandMeaning: "Transfers all refs in refs/tags/ to remote repository.",
    useCase: "Publishing releases to GitHub so users can download release tarballs.",
    searchKeywords: [
      "command to push tags",
      "git push origin --tags",
      "publish release to github",
      "upload tags",
    ],
    breakdown: [
      { token: "git", meaning: "Git CLI" },
      { token: "push", meaning: "Upload to remote" },
      { token: "origin", meaning: "Remote repository" },
      { token: "--tags", meaning: "Pushes all local tags that are not yet on remote", isFlag: true },
    ],
    realWorldEffect: "Generates official Releases on your GitHub repository page.",
    cheatSheetRef: "git-scm.com/cheat-sheet (Tagging)",
  },
  {
    id: "reflog-rescue",
    category: "Rebase & Advanced",
    name: "View Reflog to Rescue Lost Commits",
    cmd: "git reflog",
    summary: "Shows the chronological log of all HEAD movements (commits, resets, checkouts) to rescue 'lost' commits.",
    commandMeaning: "Reads local HEAD reflog history. Even deleted commits or broken rebases can be recovered here.",
    useCase: "The ultimate Git safety net: Recovering code after an accidental 'git reset --hard' or bad rebase.",
    searchKeywords: [
      "command to rescue lost commits",
      "git reflog",
      "recover deleted commit",
      "undo git reset hard",
      "rescue git disaster",
      "find lost branch",
    ],
    breakdown: [
      { token: "git", meaning: "Git CLI" },
      { token: "reflog", meaning: "Reference logs recording whenever branch tips or HEAD update" },
    ],
    realWorldEffect: "Shows all past HEAD positions (e.g. HEAD@{2}). You can run 'git reset --hard HEAD@{2}' to recover anything.",
    cheatSheetRef: "git-scm.com/cheat-sheet (Advanced)",
  },
  {
    id: "bisect-debug",
    category: "Rebase & Advanced",
    name: "Binary Search to Find Regression Bug (git bisect)",
    cmd: "git bisect start && git bisect bad && git bisect good v1.0.0",
    summary: "Uses binary search through commit history to automatically pinpoint the exact commit that introduced a bug.",
    commandMeaning: "Bisects commit range logarithmically, checking out intermediate commits for testing.",
    useCase: "Finding which commit broke a feature when you have hundreds of commits between working and broken state.",
    searchKeywords: [
      "command to find bug in history",
      "git bisect",
      "binary search bug",
      "which commit broke",
      "find regression commit",
      "bisect debug",
    ],
    breakdown: [
      { token: "git", meaning: "Git CLI" },
      { token: "bisect", meaning: "Binary search tool" },
      { token: "start", meaning: "Begins bisect wizard" },
      { token: "bad", meaning: "Marks current commit as broken" },
      { token: "good", meaning: "Marks known working commit hash/tag" },
    ],
    realWorldEffect: "Splits history in half repeatedly until it names the exact commit that introduced the bug.",
    cheatSheetRef: "git-scm.com/cheat-sheet (Advanced)",
  },
];

/**
 * Intelligent Multi-Token & Intent Matching Search
 */
export function searchCheatSheet(
  query: string,
  category: CheatSheetCategory,
  commands: CheatSheetCommand[] = gitCheatSheetCommands
): { command: CheatSheetCommand; score: number }[] {
  const trimmedQuery = query.trim().toLowerCase();

  return commands
    .map((cmd) => {
      // Category filter check
      if (category !== "All" && cmd.category !== category) {
        return { command: cmd, score: -1 };
      }

      if (!trimmedQuery) {
        return { command: cmd, score: 1 };
      }

      let score = 0;

      // 1. Direct Command match
      if (cmd.cmd.toLowerCase() === trimmedQuery) score += 100;
      else if (cmd.cmd.toLowerCase().includes(trimmedQuery)) score += 50;

      // 2. Direct Name match
      if (cmd.name.toLowerCase().includes(trimmedQuery)) score += 40;

      // 3. Search Keywords / Intent Match
      for (const kw of cmd.searchKeywords) {
        const kwLower = kw.toLowerCase();
        if (kwLower === trimmedQuery) {
          score += 60;
        } else if (kwLower.includes(trimmedQuery) || trimmedQuery.includes(kwLower)) {
          score += 35;
        }
      }

      // 4. Meaning & Summary match
      if (cmd.commandMeaning.toLowerCase().includes(trimmedQuery)) score += 20;
      if (cmd.summary.toLowerCase().includes(trimmedQuery)) score += 15;
      if (cmd.useCase.toLowerCase().includes(trimmedQuery)) score += 15;

      // 5. Token-by-token multi-word search (e.g. "command to add file" -> ["command", "add", "file"])
      const queryTokens = trimmedQuery.split(/\s+/).filter((t) => t.length > 1);
      if (queryTokens.length > 1) {
        let tokenMatches = 0;
        for (const qt of queryTokens) {
          // ignore generic stop words in scoring weight
          const isStopWord = ["to", "a", "the", "in", "of", "and", "or", "for", "is"].includes(qt);
          
          let matched = false;
          if (cmd.cmd.toLowerCase().includes(qt)) {
            matched = true;
            score += isStopWord ? 2 : 15;
          }
          if (cmd.name.toLowerCase().includes(qt)) {
            matched = true;
            score += isStopWord ? 2 : 12;
          }
          if (cmd.searchKeywords.some((k) => k.toLowerCase().includes(qt))) {
            matched = true;
            score += isStopWord ? 2 : 15;
          }
          if (cmd.commandMeaning.toLowerCase().includes(qt)) {
            matched = true;
            score += isStopWord ? 1 : 8;
          }
          if (matched && !isStopWord) tokenMatches++;
        }

        // Bonus if all query tokens matched
        if (tokenMatches >= Math.min(queryTokens.length, 3)) {
          score += 25;
        }
      }

      return { command: cmd, score };
    })
    .filter((res) => res.score > 0)
    .sort((a, b) => b.score - a.score);
}
